#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config auto_alternate       true

# ========================================
#      BSPWM WINDOW DECORATION COLORS
# ========================================
bspc config active_border_color "#2C2E34"
bspc config normal_border_color "#2C2E34"
bspc config focused_border_color "#F39660"

# ===== MOVING FLOATING WINDOWS IN 144 Hz ===== #
bspc config pointer_motion_interval 7ms

# =============================
#      AUTO START COMMANDS
# =============================
setxkbmap dk
feh --bg-scale --randomize ~/Pictures/wallpapers/* &

# ===== POLYBAR LAUNCH ===== #
~/.config/polybar/launch.sh &

bspc rule -a MiBar state=floating
bspc rule -a MiBar manage=off
